name: bento

# Anchors:
x-base-environment: &base-environment
  DATABASE_URL: postgresql://${POSTGRES_USER:-worker}:${POSTGRES_PASSWORD:-password}@${POSTGRES_HOST:-192.168.45.93}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-taskdb}
  REDIS_URL: redis://${REDIS_HOST:-redis}:6379
  S3_URL: http://${MINIO_HOST:-192.168.45.93}:9000
  S3_BUCKET: ${MINIO_BUCKET:-workflow}
  S3_ACCESS_KEY: ${MINIO_ROOT_USER:-admin}
  S3_SECRET_KEY: ${MINIO_ROOT_PASS:-password}
  RUST_LOG: ${RUST_LOG:-info}
  RUST_BACKTRACE: 1

x-agent-common: &agent-common
  image: daw8n/risc0-agent:22.04-12.9.1-120-v2.3.1-nodeinfra-gpu
  runtime: nvidia
  restart: always
  depends_on:
    - redis
  environment:
    <<: *base-environment

x-exec-agent-common: &exec-agent-common
  <<: *agent-common
  mem_limit: 16G
  cpus: 3
  runtime: nvidia
  environment:
    <<: *base-environment
    LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:-/usr/local/cuda-12.9/compat/}
    RISC0_KECCAK_PO2: ${RISC0_KECCAK_PO2:-17}
    JOIN_STREAM: 1
    COPROC_STREAM: 1
  entrypoint: /app/agent -t exec --segment-po2 ${SEGMENT_SIZE:-21} --redis-ttl ${REDIS_TTL:-57600}

services:
  redis:
    hostname: ${REDIS_HOST:-redis}
    image: ${REDIS_IMG:-redis:7.2.5-alpine3.19}
    mem_limit: 30G
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --maxmemory 28g --maxmemory-policy allkeys-lru
  exec_agent0:
    <<: *exec-agent-common

  exec_agent1:
    <<: *exec-agent-common

  exec_agent2:
    <<: *exec-agent-common

  exec_agent3:
    <<: *exec-agent-common

  exec_agent4:
    <<: *exec-agent-common

  gpu_prove_agent0:
    <<: *agent-common
    runtime: nvidia
    mem_limit: 16G
    cpus: 8
    entrypoint: /app/agent -t prove --redis-ttl ${REDIS_TTL:-57600}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
  join_agent:
    <<: *agent-common
    mem_limit: 16G
    cpus: 8
    entrypoint: /app/agent -t join --redis-ttl ${REDIS_TTL:-57600}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]

  aux_agent:
    <<: *agent-common
    mem_limit: 512M
    cpus: 2
    environment:
      <<: *base-environment
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:-/usr/local/cuda-12.9/compat/}
    entrypoint: /app/agent -t aux --monitor-requeue --redis-ttl ${REDIS_TTL:-57600}

  # SNARK Agent
  snark_agent:
    <<: *agent-common
    entrypoint: /app/agent -t snark --redis-ttl ${REDIS_TTL:-57600}
    environment:
      <<: *base-environment
      LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:-/usr/local/cuda-12.9/compat/}
    ulimits:
      # Needed for stark_verify bin
      stack: 90000000
volumes:
  redis-data: